# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Tamilselvan M'
tagline:          'Tamil Blog'
description:      'My Campus Diary Tamil blog'
url:              'http://blog.mycampusdiary.com'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Tamilselvan'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://web.facebook.com/kabil.dev.7505/'
flickr:
github:         'https://github.com/tamilselvanmariappan/'
gplus:          'https://plus.google.com/u/0/113698833873685108099'
instagram:
pinterest:
linkedin:       'https://in.linkedin.com/in/tamilselvan-mariappan-476678a3'
rss:
stackoverflow:  '#'
twitter:        'https://twitter.com/tamilmariappan'

# Google Analytics
gahandler: 'UA-67216433-2'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'blogmycampusdiarycom'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
